# This is a config for E2B sandbox template.
# You can use template ID (htmjqm8gzrlw765fvk6d) or template name (paynto-vite) to create a sandbox:

# Python SDK
# from e2b import Sandbox, AsyncSandbox
# sandbox = Sandbox.create("paynto-vite") # Sync sandbox
# sandbox = await AsyncSandbox.create("paynto-vite") # Async sandbox

# JS SDK
# import { Sandbox } from 'e2b'
# const sandbox = await Sandbox.create('paynto-vite')

team_id = "d7e89fba-22c8-46a9-beda-dc4dcba3a91f"
dockerfile = "e2b.Dockerfile"
template_name = "paynto-vite"
template_id = "htmjqm8gzrlw765fvk6d"
